version: '2.0'

services:
  angular:
    build: client
    container_name: frontend
    ports:
      - "4200:4200"
    depends_on:
      - express

  express:
    build: backend
    container_name: backend
    ports:
      - "3000:3000"
